# Generated by Django 3.1.3 on 2020-11-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0002_auto_20201124_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='studentcondition',
            name='current_selected_answers',
            field=models.ManyToManyField(blank=True, to='bot_logic.Answer'),
        ),
        migrations.AlterField(
            model_name='studentcondition',
            name='current_test',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_test', to='bot_logic.test'),
        ),
        migrations.AlterField(
            model_name='studentcondition',
            name='student',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot_logic.student'),
        ),
        migrations.AlterField(
            model_name='studentcondition',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='tests', to='bot_logic.Test'),
        ),
    ]
