# Generated by Django 3.1.3 on 2020-12-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0003_auto_20201128_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(default='Без категории'),
        ),
    ]
